module app;

import serverino;

import std;
import core.thread;

mixin ServerinoBackground;

enum PLAIN_PORT = 18080;
enum TLS_PORT   = 18443;

// Certificates are generated by preBuildCommands, next to the executable.
string certPath(string name) { return buildPath(thisExePath.dirName, name); }

void main()
{
   import core.stdc.stdlib: exit;
   import serverino.daemon;

   while(!Daemon.bootCompleted && !Daemon.bootFailed)
      Thread.sleep(10.msecs);

   if (Daemon.bootFailed)
   {
      writeln("Serverino did not start: ", Daemon.bootError);
      exit(-1);
   }

   try { test(); }
   catch (Throwable t)
   {
      writeln("Test failed");
      writeln(t);
      exit(-1);
   }

   Daemon.shutdown();
   writeln("All tests passed!");
}

@onServerInit
ServerinoConfig configure()
{
   // A plain listener and an encrypted one, in the same process.
   return ServerinoConfig.create()
      .addListener("127.0.0.1", PLAIN_PORT)
      .addListener("127.0.0.1", TLS_PORT, Https(certPath("first.crt"), certPath("first.key")))
      .enableRemoteIp()
      .setWorkers(2);
}

@endpoint @route!"/secure"
void secure(Request request, Output output) { output ~= request.isSecure ? "secure" : "insecure"; }

@endpoint @route!"/remote-ip"
void remoteIp(Request request, Output output) { output ~= request.header.read("x-remote-ip", "<none>"); }

// ----------------------------------------------------------------------------

auto client()
{
   auto http = HTTP();
   http.verifyPeer = false;
   http.handle.set(CurlOption.ssl_verifyhost, 0);
   return http;
}

string plain(string path) { return cast(string) get("http://127.0.0.1:" ~ PLAIN_PORT.to!string ~ path, client()); }
string tls(string path) { return cast(string) get("https://127.0.0.1:" ~ TLS_PORT.to!string ~ path, client()); }

// Subject of the certificate served right now, read with openssl s_client.
string servedSubject()
{
   auto res = executeShell("openssl s_client -connect 127.0.0.1:" ~ TLS_PORT.to!string ~
      " -servername first.test </dev/null 2>/dev/null | openssl x509 -noout -subject");
   return res.output.strip;
}

void test()
{
   // ---- (1) plain and encrypted listeners live together, and isSecure tells them apart
   assert(plain("/secure") == "insecure", "plain listener: " ~ plain("/secure"));
   assert(tls("/secure") == "secure", "tls listener: " ~ tls("/secure"));

   // ---- (2) isSecure can't be forged by the client
   auto forged = HTTP();
   forged.addRequestHeader("x-forwarded-proto", "https");
   forged.addRequestHeader("x-secure", "1");
   assert((cast(string) get("http://127.0.0.1:" ~ PLAIN_PORT.to!string ~ "/secure", forged)) == "insecure");

   // ...and neither can the remote ip injected by the daemon
   auto spoofed = HTTP();
   spoofed.addRequestHeader("x-remote-ip", "6.6.6.6");
   auto ip = (cast(string) get("http://127.0.0.1:" ~ PLAIN_PORT.to!string ~ "/remote-ip", spoofed)).strip;
   assert(ip == "127.0.0.1", "x-remote-ip spoofed: " ~ ip);

   // ---- (3) keep-alive: every request on the same encrypted connection is secure
   {
      auto keepAlive = client();
      foreach(_; 0..3)
         assert((cast(string) get("https://127.0.0.1:" ~ TLS_PORT.to!string ~ "/secure", keepAlive)) == "secure");
   }

   // ---- (4) communicators are pooled and reused: a plain connection must never
   //          inherit the TLS state of the previous one, nor the other way around
   foreach(_; 0..8)
   {
      assert(plain("/secure") == "insecure", "communicator reuse: plain request served as secure");
      assert(tls("/secure") == "secure", "communicator reuse: encrypted request served as insecure");
   }

   // ---- (5) hot reload of the certificates
   immutable before = servedSubject();

   // A brand new certificate, with a name nobody used before: overwrite the ones in use
   immutable newName = "reloaded-" ~ Clock.currTime.toUnixTime.to!string ~ ".test";
   auto generated = execute(["openssl", "req", "-x509", "-newkey", "rsa:2048",
      "-keyout", certPath("first.key"), "-out", certPath("first.crt"),
      "-days", "2", "-nodes", "-subj", "/CN=" ~ newName]);
   assert(generated.status == 0, "cannot generate a new certificate: " ~ generated.output);
   assert(!before.canFind(newName));

   import serverino.daemon : Daemon;
   Daemon.reloadCertificates();

   string after;
   foreach(_; 0..50)
   {
      Thread.sleep(200.msecs);
      after = servedSubject();
      if (after.canFind(newName)) break;
   }

   assert(after.canFind(newName), "certificates not reloaded: " ~ after ~ " (was: " ~ before ~ ")");

   // the server never restarted: it still answers on both listeners
   assert(plain("/secure") == "insecure");
   assert(tls("/secure") == "secure");
}
