# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: BUILD & TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest, ubuntu-24.04-arm]
        dc: [ldc-latest, dmd-2.109.0]
        exclude:
        - os: ubuntu-24.04-arm
          dc: dmd-2.109.0
        - os: macos-14
          dc: dmd-2.109.0
        - os: macos-13
          dc: ldc-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run sanity checks
        if: ${{ matrix.dc != 'ldc-latest' }}
        run: echo "import serverino; mixin ServerinoMain; @endpoint void a(Output o) { }" | dmd -i -Isource -ofinline_1 - &&
             echo "import serverino; mixin ServerinoMain; @endpoint void a(Request r, Output o) { }" | dmd -i -Isource -ofinline_2 - &&
             echo "import serverino; mixin ServerinoMain; @endpoint void a(Request r) { }" | dmd -i -Isource -ofinline_3 - &&
             echo "import serverino; mixin ServerinoBackground; @endpoint void a(Request r) { } void main() { }" | dmd -i -Isource -ofinline_4 -


      - name: Run test-01
        run: dub run --root=tests/test-01

      - name: Run test-02
        run: dub run --root=tests/test-02

      - name: Run test-03
        run: dub run --root=tests/test-03

      - name: Build examples
        run: dub build --build=release --root=examples/01_hello_world/
              && dub build --root=examples/02_priority/
              && dub build --root=examples/03_form/
              && dub build --root=examples/04_html_dom/
              && dub build --root=examples/05_websocket_echo/
              && dub build --root=examples/06_websocket_noise_stream/
              && dub build --root=examples/07_websocket_callback/
              && dub build --root=examples/08_cmdline_args/
              && dub build --root=examples/09_simple_session/
              && dub build --root=examples/10_diet_ng_templates/
              && dub build --root=examples/11_elemi_integration/
